// 小学四年级英语词汇数据 - 自动生成自 words/四年级单词.xlsx
// 生成时间: 2026-06-12
// 上册: Unit 1-5, 下册: Unit 6-13, 每单元 20 个单词
// 不足部分由同册单词随机重复补全

const LEVEL_DATA = [
  {
    id: 1,
    name: "Unit 1",
    timeLimit: 900,
    words: [
      { en: "afraid", zh: "害怕的" },
      { en: "doctor", zh: "医生" },
      { en: "read", zh: "读" },
      { en: "dentist", zh: "牙科医生" },
      { en: "fireman", zh: "消防队员" },
      { en: "shop assistant", zh: "营业员" },
      { en: "sing", zh: "唱" },
      { en: "waitress", zh: "女服务员" },
      { en: "draw", zh: "画" },
      { en: "policewoman", zh: "女警察" },
      { en: "waiter", zh: "男服务员" },
      { en: "our", zh: "我们的" },
      { en: "brush", zh: "刷子" },
      { en: "policeman", zh: "警察" },
      { en: "cook", zh: "烹调，厨师" },
      { en: "swim", zh: "游泳" },
      { en: "fire", zh: "火" },
      { en: "engine", zh: "引擎" },
      { en: "classmate", zh: "同学" },
      { en: "dear", zh: "亲爱的" },
    ],
  },
  {
    id: 2,
    name: "Unit 2",
    timeLimit: 900,
    words: [
      { en: "tooth", zh: "脚趾" },
      { en: "knee", zh: "膝盖" },
      { en: "brave", zh: "勇敢的" },
      { en: "sharp", zh: "尖的" },
      { en: "shoulder", zh: "肩膀" },
      { en: "…years old", zh: "……岁" },
      { en: "bell", zh: "铃" },
      { en: "tired", zh: "累的" },
      { en: "face", zh: "手脸" },
      { en: "bookshop", zh: "书店" },
      { en: "block", zh: "大楼" },
      { en: "argry", zh: "气愤的" },
      { en: "branch", zh: "树枝" },
      { en: "round", zh: "圆的" },
      { en: "yours", zh: "pron.你的" },
      { en: "full", zh: "饱的" },
      { en: "stronger", zh: "强壮的" },
      { en: "butter", zh: "黄油" },
      { en: "foot", zh: "脚" },
      { en: "You can call me", zh: "你可以叫我……(名字)" },
    ],
  },
  {
    id: 3,
    name: "Unit 3",
    timeLimit: 900,
    words: [
      { en: "thirteen", zh: "十三" },
      { en: "bread", zh: "面包" },
      { en: "fifty", zh: "五十" },
      { en: "coffee", zh: "咖啡" },
      { en: "seventeen", zh: "十七" },
      { en: "feed", zh: "喂" },
      { en: "fourteen", zh: "十四" },
      { en: "exercise", zh: "游泳池" },
      { en: "sixteen", zh: "十六" },
      { en: "eighteen", zh: "十八" },
      { en: "flour", zh: "面粉" },
      { en: "nineteen", zh: "十九" },
      { en: "twenty", zh: "二十" },
      { en: "eleven", zh: "十一" },
      { en: "thirty", zh: "三十" },
      { en: "chocolate", zh: "巧克力" },
      { en: "twelve", zh: "十二" },
      { en: "forty", zh: "四十" },
      { en: "fifteen", zh: "十五" },
      { en: "crisps", zh: "油炸饼干(片)" },
    ],
  },
  {
    id: 4,
    name: "Unit 4",
    timeLimit: 900,
    words: [
      { en: "pick", zh: "摘" },
      { en: "rectangle", zh: "长方形" },
      { en: "water", zh: "水" },
      { en: "sunglasses", zh: "太阳眼镜" },
      { en: "plant", zh: "植物" },
      { en: "hoop", zh: "呼啦圈" },
      { en: "juice", zh: "果汁" },
      { en: "square", zh: "正方形" },
      { en: "packet", zh: "小包" },
      { en: "glass", zh: "玻璃杯" },
      { en: "answer", zh: "回答" },
      { en: "case", zh: "盒" },
      { en: "fruit", zh: "水果" },
      { en: "sketch-book", zh: "写生簿" },
      { en: "rope", zh: "绳子" },
      { en: "grass", zh: "草地" },
      { en: "pond", zh: "水池" },
      { en: "walk", zh: "走" },
      { en: "under", zh: "在……下面" },
      { en: "thirteen", zh: "十三" },
    ],
  },
  {
    id: 5,
    name: "Unit 5",
    timeLimit: 900,
    words: [
      { en: "everywhere", zh: "到处" },
      { en: "mask", zh: "面具" },
      { en: "leave", zh: "丢下" },
      { en: "game", zh: "游戏" },
      { en: "bowl", zh: "碗" },
      { en: "throw", zh: "扔" },
      { en: "stone", zh: "石头" },
      { en: "log", zh: "圆木" },
      { en: "hay", zh: "干草" },
      { en: "shop", zh: "商店" },
      { en: "question", zh: "问题" },
      { en: "cow", zh: "奶牛" },
      { en: "farm", zh: "农场" },
      { en: "horse", zh: "马" },
      { en: "rubbish", zh: "垃圾" },
      { en: "trunk", zh: "树干" },
      { en: "into", zh: "到……里" },
      { en: "their", zh: "他们的" },
      { en: "feed", zh: "喂" },
      { en: "win", zh: "获胜" },
    ],
  },
  {
    id: 6,
    name: "Unit 6",
    timeLimit: 900,
    words: [
      { en: "donkey", zh: "驴" },
      { en: "piano", zh: "钢琴" },
      { en: "behind", zh: "在……后" },
      { en: "music", zh: "音乐" },
      { en: "hole", zh: "洞" },
      { en: "basket", zh: "篮子" },
      { en: "beside", zh: "在……旁边" },
      { en: "felt pen", zh: "毡头笔" },
      { en: "old", zh: "旧的" },
      { en: "kitchen", zh: "厨房" },
      { en: "drum", zh: "鼓" },
      { en: "hamburger", zh: "汉堡包" },
      { en: "thick", zh: "厚的" },
      { en: "guitar", zh: "吉他" },
      { en: "recorder", zh: "八孔直笛、录音机" },
      { en: "grape", zh: "葡萄" },
      { en: "brush", zh: "画笔，毛笔" },
      { en: "sleep", zh: "睡觉" },
      { en: "scissors", zh: "剪刀" },
      { en: "blind", zh: "盲的" },
    ],
  },
  {
    id: 7,
    name: "Unit 7",
    timeLimit: 900,
    words: [
      { en: "homework", zh: "家庭作业" },
      { en: "motor-bike", zh: "摩托车" },
      { en: "triangle", zh: "(一种乐器)三角形" },
      { en: "class", zh: "班" },
      { en: "thing", zh: "东西" },
      { en: "drive", zh: "驾驶" },
      { en: "pilot", zh: "飞行员" },
      { en: "children", zh: "孩子们" },
      { en: "restaurant", zh: "餐馆" },
      { en: "dining", zh: "就餐" },
      { en: "pizza", zh: "比萨饼" },
      { en: "busy", zh: "繁忙的" },
      { en: "violin", zh: "提琴" },
      { en: "letter", zh: "字母" },
      { en: "bathroom", zh: "浴室" },
      { en: "thin", zh: "薄的" },
      { en: "football", zh: "足球" },
      { en: "cousin", zh: "表(堂)兄弟，表(堂)姐妹" },
      { en: "bedroom", zh: "卧室" },
      { en: "help", zh: "帮助" },
    ],
  },
  {
    id: 8,
    name: "Unit 8",
    timeLimit: 900,
    words: [
      { en: "November", zh: "十一月" },
      { en: "September", zh: "九月" },
      { en: "shaker", zh: "摇动器" },
      { en: "January", zh: "一月" },
      { en: "lesson", zh: "课" },
      { en: "February", zh: "二月" },
      { en: "April", zh: "四月" },
      { en: "month", zh: "月" },
      { en: "March", zh: "三月" },
      { en: "above", zh: "在……上面" },
      { en: "soldier", zh: "士兵" },
      { en: "August", zh: "八月" },
      { en: "watch", zh: "观看" },
      { en: "October", zh: "十月" },
      { en: "spaceship", zh: "宇宙飞船" },
      { en: "uncle", zh: "叔叔" },
      { en: "July", zh: "七月" },
      { en: "student", zh: "学生" },
      { en: "June", zh: "六月" },
      { en: "sitting-room", zh: "起居室" },
    ],
  },
  {
    id: 9,
    name: "Unit 9",
    timeLimit: 900,
    words: [
      { en: "December", zh: "十二月" },
      { en: "Monday", zh: "星期一" },
      { en: "Wednesday", zh: "星期三" },
      { en: "cycling", zh: "骑车" },
      { en: "Tuesday", zh: "星期二" },
      { en: "Thursday", zh: "星期四" },
      { en: "hot", zh: "热的" },
      { en: "Saturday", zh: "星期六" },
      { en: "sail", zh: "驾驶(船只)" },
      { en: "no ball", zh: "网球" },
      { en: "back", zh: "背部" },
      { en: "sunny", zh: "阳光充足的" },
      { en: "Friday", zh: "星期五" },
      { en: "rainy", zh: "下雨的" },
      { en: "cloudy", zh: "多云的" },
      { en: "buy", zh: "买" },
      { en: "swan", zh: "天鹅" },
      { en: "football", zh: "足球" },
      { en: "Sunday", zh: "星期日" },
      { en: "between", zh: "在……中间" },
    ],
  },
  {
    id: 10,
    name: "Unit 10",
    timeLimit: 900,
    words: [
      { en: "meat", zh: "肉" },
      { en: "noodle", zh: "面条" },
      { en: "get", zh: "拿，取" },
      { en: "crisp", zh: "脆的" },
      { en: "need", zh: "需要" },
      { en: "weather", zh: "天气" },
      { en: "get on", zh: "穿上" },
      { en: "Here are…", zh: "(复数名词)这儿有……" },
      { en: "thunder", zh: "雷声" },
      { en: "time", zh: "时间" },
      { en: "dear", zh: "昂贵的" },
      { en: "bake", zh: "烤" },
      { en: "flour", zh: "面粉" },
      { en: "bread", zh: "面包" },
      { en: "get up", zh: "起床" },
      { en: "drink", zh: "喝" },
      { en: "cheap", zh: "便宜的" },
      { en: "watch", zh: "观看" },
      { en: "wear", zh: "穿" },
      { en: "French fries", zh: "炸薯条" },
    ],
  },
  {
    id: 11,
    name: "Unit 11",
    timeLimit: 900,
    words: [
      { en: "sign", zh: "标志" },
      { en: "dear", zh: "昂贵的" },
      { en: "twentieth", zh: "第二十" },
      { en: "eighty", zh: "八十" },
      { en: "salt", zh: "盐" },
      { en: "thirty-first", zh: "第三十一" },
      { en: "eighth", zh: "第八" },
      { en: "scissors", zh: "剪刀" },
      { en: "sixty", zh: "六十" },
      { en: "paper", zh: "纸" },
      { en: "twelfth", zh: "第十二" },
      { en: "rice", zh: "米饭" },
      { en: "ninety", zh: "九十" },
      { en: "buy", zh: "买" },
      { en: "thunder", zh: "雷声" },
      { en: "every", zh: "每一" },
      { en: "seventy", zh: "七十" },
      { en: "when", zh: "什么时候" },
      { en: "fifty", zh: "五十" },
      { en: "paint", zh: "颜料" },
    ],
  },
  {
    id: 12,
    name: "Unit 12",
    timeLimit: 900,
    words: [
      { en: "by", zh: "通过" },
      { en: "lesson", zh: "课" },
      { en: "become", zh: "变成" },
      { en: "timetable", zh: "时间表" },
      { en: "aquarium", zh: "水族馆" },
      { en: "China", zh: "中国" },
      { en: "floor", zh: "地板" },
      { en: "dangerous", zh: "危险的" },
      { en: "bake", zh: "烤" },
      { en: "quarter", zh: "一刻钟" },
      { en: "Why", zh: "为什么" },
      { en: "music", zh: "音乐" },
      { en: "sharp", zh: "锋利的" },
      { en: "old", zh: "旧的" },
      { en: "country", zh: "国家" },
      { en: "early", zh: "早的" },
      { en: "subject", zh: "科目" },
      { en: "painting", zh: "油画" },
      { en: "money", zh: "钱" },
      { en: "Chinese", zh: "汉语" },
    ],
  },
  {
    id: 13,
    name: "Unit 13",
    timeLimit: 900,
    words: [
      { en: "wing", zh: "翅膀" },
      { en: "plant", zh: "植物" },
      { en: "cocoon", zh: "茧" },
      { en: "body", zh: "身体" },
      { en: "insect", zh: "昆虫" },
      { en: "ocean", zh: "海洋" },
      { en: "keeper", zh: "饲养员" },
      { en: "touch", zh: "触摸" },
      { en: "fisherman", zh: "渔民" },
      { en: "Chinese", zh: "汉语" },
      { en: "frog", zh: "青蛙" },
      { en: "thin", zh: "薄的" },
      { en: "jellyfish", zh: "水母" },
      { en: "spaceship", zh: "宇宙飞船" },
      { en: "shell", zh: "贝壳；蛹子" },
      { en: "dive", zh: "跳水" },
      { en: "their", zh: "他们的" },
      { en: "feather", zh: "羽毛" },
      { en: "caterpillar", zh: "毛虫" },
      { en: "land", zh: "陆地" },
    ],
  },
];

// 可配置参数
const GAME_CONFIG = {
  timePenalty: 5, // 配对错误扣除秒数
  maxLeaderboardEntries: 10,
  defaultTimeLimit: 920,
};
